version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://teamprojectmccewenseager.ue.r.appspot.com
    # For development, you can use volumes to enable hot reloading
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
